export const companyData = [
  {
    id: "company-001",
    name: "テックイノベーション株式会社",
    description:
      "最先端のWeb技術を駆使したサービス開発を行うテクノロジー企業です。",
    industry: "IT・ソフトウェア",
    logoUrl: "/companies/company01.jpg",
    headerImageUrl: "/companies/company01-header.jpg",
    websiteUrl: "https://example.com/tech-innovation",
    location: "東京都渋谷区",
    size: "medium",
    foundedYear: 2010,
    email: "recruit@tech-innovation.example.com",
    phone: "03-1234-5678",
    employeeCount: 100,
  },
  {
    id: "company-002",
    name: "フューチャーデベロップメント",
    description: "スタートアップ支援とウェブサービス開発に特化した企業です。",
    industry: "IT・Webサービス",
    logoUrl: "/companies/company02.jpg",
    headerImageUrl: "/companies/company02-header.jpg",
    websiteUrl: "https://example.com/future-dev",
    location: "大阪府大阪市",
    size: "small",
    foundedYear: 2015,
    email: "jobs@future-dev.example.com",
    employeeCount: 50,
  },
  {
    id: "company-003",
    name: "データサイエンスラボ",
    description: "AIと機械学習を活用したデータ分析サービスを提供する企業です。",
    industry: "データサイエンス・AI",
    logoUrl: "/companies/company03.jpg",
    headerImageUrl: "/companies/company03-header.jpg",
    websiteUrl: "https://example.com/data-science-lab",
    location: "東京都千代田区",
    size: "small",
    foundedYear: 2018,
    email: "careers@datasciencelab.example.com",
    employeeCount: 30,
  },
  {
    id: "company-004",
    name: "モバイルクリエイト",
    description:
      "革新的なモバイルアプリケーションを開発するスタートアップ企業です。",
    industry: "モバイルアプリ開発",
    logoUrl: "/companies/company04.jpg",
    headerImageUrl: "/companies/company04-header.jpg",
    websiteUrl: "https://example.com/mobile-create",
    location: "東京都新宿区",
    size: "startup",
    foundedYear: 2020,
    email: "hello@mobilecreate.example.com",
    employeeCount: 10,
  },
  {
    id: "company-005",
    name: "クラウドソリューションズ",
    description: "クラウドインフラの構築・運用を支援するITサービス企業です。",
    industry: "クラウドサービス・インフラ",
    logoUrl: "/companies/company05.jpg",
    headerImageUrl: "/companies/company05-header.jpg",
    websiteUrl: "https://example.com/cloud-solutions",
    location: "福岡県福岡市",
    size: "medium",
    foundedYear: 2012,
    email: "recruiting@cloudsolutions.example.com",
    phone: "092-987-6543",
    employeeCount: 20,
  },
];
